version: '1'
services:
  kafka-cluster:
    image: landoop/fast-data-dev:cp3.3.0
    environment:
      ADV_HOST: 127.0.0.1         # Mudar para 192.168.99.100 caso esteja usando o Docker Toolbox
      RUNTESTS: 0                 # Desabilitar os testes para ser mais rápido
      FORWARDLOGS: 0              # Desabilitar os logs (5 arquivos)
      SAMPLEDATA: 0               # Não criar os exemplos
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker